name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v4

    - name: Python 설치
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 라이브러리 설치
      run: |
        pip install -r requirements.txt

    - name: exe 빌드
      run: |
        pyinstaller --onefile --name ExcelDiff --console false excel_diff_app/__main__.py

    - name: 결과 업로드
      uses: actions/upload-artifact@v4
      with:
        name: ExcelDiff
        path: dist/ExcelDiff.exe
